import * as T from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {DRACOLoader} from 'three/addons/loaders/DRACOLoader.js';
import {RoundedBoxGeometry} from 'three/addons/geometries/RoundedBoxGeometry.js';
export async function loadCar(scene,progress){
 const draco=new DRACOLoader();draco.setDecoderPath(`${import.meta.env.BASE_URL}draco/`);const loader=new GLTFLoader().setDRACOLoader(draco);
 const gltf=await loader.loadAsync(`${import.meta.env.BASE_URL}models/porsche-911.glb`,e=>progress(e.total?e.loaded/e.total:.7));draco.dispose();
 const car=new T.Group();const model=gltf.scene;const ground=model.getObjectByName('Plane');if(ground)ground.removeFromParent();model.updateMatrixWorld(true);const bounds=new T.Box3().setFromObject(model),size=bounds.getSize(new T.Vector3());const scale=4.65/Math.max(size.x,size.z);model.scale.multiplyScalar(scale);model.updateMatrixWorld(true);const b=new T.Box3().setFromObject(model),center=b.getCenter(new T.Vector3());model.position.x-=center.x;model.position.z-=center.z;model.position.y-=b.min.y-.015;car.add(model);scene.add(car);
 const paint=new T.MeshPhysicalMaterial({color:'#fc650a',metalness:.64,roughness:.23,clearcoat:1,clearcoatRoughness:.1,envMapIntensity:1.35});
 const carbon=new T.MeshPhysicalMaterial({color:'#14171a',metalness:.55,roughness:.32,clearcoat:.7}),alloy=new T.MeshStandardMaterial({color:'#424448',metalness:.93,roughness:.24});
 const bodyMaterials=new Set(),lights=[],meshes=[];
 model.traverse(o=>{if(!o.isMesh)return;o.castShadow=true;o.receiveShadow=true;meshes.push(o);let name=o.material.name;let m=o.material.clone();if(name==='paint'||name==='coat'){m=paint;o.userData.body=true;bodyMaterials.add(m)}else if(name==='silver'){m=alloy}else if(name==='window'){m=new T.MeshPhysicalMaterial({color:'#405264',metalness:.25,roughness:.08,transparent:true,opacity:.6,clearcoat:1,envMapIntensity:1.8,side:T.DoubleSide});bodyMaterials.add(m)}else if(name==='rubber'){m.color.set('#17191a');m.roughness=.86;m.metalness=0}else if(name==='lights'){m.emissive=new T.Color('#cadfff');m.emissiveIntensity=.8;lights.push(m)}else if(name==='glass'){m.transparent=true;m.opacity=.38;m.roughness=.08;m.metalness=.25}m.name=name;o.material=m;});
 const add=(geo,mat,pos,parent=car)=>{let o=new T.Mesh(geo,mat);o.position.set(...pos);o.castShadow=true;o.receiveShadow=true;parent.add(o);return o};
 const box=(w,h,d,mat,pos,parent=car)=>add(new RoundedBoxGeometry(w,h,d,2,.018),mat,pos,parent);
 // Added motorsport aerodynamic package, separate from the licensed base model.
 const wing=new T.Group();wing.userData.part='wing';car.add(wing);for(const x of [-.58,.58]){let p=box(.045,.45,.2,carbon,[x,1.12,-1.77],wing);p.rotation.x=-.2}let blade=box(1.99,.065,.37,carbon,[0,1.39,-1.88],wing);blade.rotation.x=-.09;for(const x of [-1.02,1.02]){box(.035,.21,.49,carbon,[x,1.41,-1.87],wing)}
 const splitter=box(1.83,.034,.28,carbon,[0,.19,2.08]);splitter.userData.part='headlight';for(const x of [-.94,.94]){box(.085,.06,2.6,carbon,[x,.18,-.05]);for(let k=0;k<3;k++){const l=box(.24,.012,.027,carbon,[x*.69,.91-k*.007,1.13+k*.08]);l.rotation.x=-.2}}for(const x of [-.23,.23]){let intake=box(.19,.018,.33,carbon,[x,.805,1.42]);intake.rotation.x=-.17}
 const labelCanvas=document.createElement('canvas');labelCanvas.width=1024;labelCanvas.height=128;let ctx=labelCanvas.getContext('2d');ctx.fillStyle='#141519';ctx.font='italic 900 87px Arial';ctx.textAlign='center';ctx.fillText('GT3 RS',510,91);const decalTex=new T.CanvasTexture(labelCanvas);decalTex.colorSpace=T.SRGBColorSpace;for(const s of [-1,1]){let label=add(new T.PlaneGeometry(1.12,.15),new T.MeshBasicMaterial({map:decalTex,transparent:true,depthWrite:false,polygonOffset:true,polygonOffsetFactor:-1}),[s*.923,.36,-.23]);label.rotation.y=s*Math.PI/2;}
 // Technical components use their own geometry and can be seen through the body.
 const technical=new T.Group();technical.visible=false;car.add(technical);const holo=new T.MeshStandardMaterial({color:'#3cbed7',emissive:'#1584a9',emissiveIntensity:.48,metalness:.5,roughness:.35,transparent:true,opacity:.9});const copper=new T.MeshStandardMaterial({color:'#ff8a2d',emissive:'#d34d0a',emissiveIntensity:.3,metalness:.6,roughness:.35});
 box(.53,.38,.72,holo,[0,.53,-1.48],technical);for(let side of [-1,1])for(let i=0;i<3;i++){let cylinder=add(new T.CylinderGeometry(.125,.125,.42,20),copper,[side*.36,.52,-1.24-i*.21],technical);cylinder.rotation.z=Math.PI/2;box(.22,.065,.64,holo,[side*.49,.71,-1.46],technical)}box(.28,.28,.6,holo,[0,.44,-.82],technical);
 for(const z of [-1.44,1.27]){let axle=add(new T.CylinderGeometry(.035,.035,1.7,12),copper,[0,.37,z],technical);axle.rotation.z=Math.PI/2;for(const s of [-1,1]){const disc=add(new T.CylinderGeometry(.24,.24,.045,36),holo,[s*.86,.38,z],technical);disc.rotation.z=Math.PI/2;const caliper=box(.1,.23,.12,new T.MeshStandardMaterial({color:'#ffd23f',metalness:.5,roughness:.3}),[s*.91,.41,z+.2]);caliper.userData.part='brakes';const springPoints=[];for(let k=0;k<110;k++){let a=k/110*Math.PI*14;springPoints.push(new T.Vector3(s*.67+.055*Math.sin(a),.38+k*.003,z+.055*Math.cos(a)))}add(new T.TubeGeometry(new T.CatmullRomCurve3(springPoints),110,.012,5,false),copper,[0,0,0],technical)}}
 for(const s of [-1,1]){let points=[[s*.42,.35,-1.46],[s*.63,.25,-1.85],[s*.28,.2,-2.08]].map(p=>new T.Vector3(...p));add(new T.TubeGeometry(new T.CatmullRomCurve3(points),24,.045,10,false),alloy,[0,0,0],technical)}
 const airflow=new T.Group();airflow.visible=false;car.add(airflow);const streamMat=new T.MeshBasicMaterial({color:'#5be2ff',transparent:true,opacity:.35});for(let x=-.8;x<=.8;x+=.22){let pts=[[x,1,2.7],[x,1.7,.6],[x,1.65,-.8],[x,1.57,-1.9],[x,1.25,-3.3]].map(p=>new T.Vector3(...p));add(new T.TubeGeometry(new T.CatmullRomCurve3(pts),55,.008,5,false),streamMat,[0,0,0],airflow)}
 const particles=[];for(let i=0;i<22;i++){let p=add(new T.SphereGeometry(.018,5,4),new T.MeshBasicMaterial({color:'#c0f4ff'}),[0,0,0],airflow);p.userData.phase=i/22;particles.push(p)}
 const original=new Map();bodyMaterials.forEach(m=>original.set(m,{transparent:m.transparent,opacity:m.opacity,depthWrite:m.depthWrite}));
 function setTechnical(on){technical.visible=on;bodyMaterials.forEach(m=>{const prev=original.get(m);m.transparent=on?true:prev.transparent;m.opacity=on?.13:prev.opacity;m.depthWrite=on?false:prev.depthWrite;m.needsUpdate=true})}
 return{car,model,paint,meshes,bodyMaterials,lights,technical,airflow,particles,setTechnical,bounds:new T.Box3().setFromObject(model)};
}
