export const icons={home:'<path d="m3 10 9-7 9 7v11h-7v-7h-4v7H3z"/>',gear:'<path d="m9 3-1 3-3 1-2 3 2 2-1 4 3 2 3-1 3 2 3-2 3-1v-4l2-3-2-3-4-1-2-2z"/><circle cx="12" cy="12" r="3"/>',car:'<path d="m3 10 3-5h11l4 5v7H3zM3 10h18M7 17v3m10-3v3M6 13h2m8 0h2"/>',people:'<circle cx="9" cy="7" r="3"/><circle cx="17" cy="8" r="2.5"/><path d="M2 21v-3a7 7 0 0 1 14 0v3H2m14-8a6 6 0 0 1 6 6v2h-6"/>',search:'<circle cx="10" cy="10" r="6"/><path d="m15 15 6 6"/>',menu:'<path d="M3 6h18M3 12h18M3 18h18"/>',layers:'<path d="m12 3 10 5-10 5L2 8zm-10 10 10 5 10-5M2 18l10 5 10-5"/>',volume:'<path d="M3 9h4l5-5v16l-5-5H3zM16 8a6 6 0 0 1 0 8m3-11a10 10 0 0 1 0 14"/>',tool:'<path d="M15 3a6 6 0 0 0-6 8L2 18a3 3 0 0 0 4 4l8-8a6 6 0 0 0 7-8l-5 5-3-3 4-5z"/>',lift:'<path d="M4 2v20M20 2v20M1 22h7m8 0h7M4 16h16M7 16v-4l2-4h6l2 4v4M4 5h16"/>',wheel:'<circle cx="12" cy="12" r="9"/><circle cx="12" cy="12" r="3"/><path d="M12 3v6m0 6v6M3 12h6m6 0h6m-9-6 4 4m4 4 4 4m0-12-4 4m-4 4-4 4"/>',light:'<path d="M12 5a7 7 0 0 0 0 14zm4 0h6m-6 5h6m-6 4h6m-6 5h6"/>',glass:'<path d="M6 4h12l4 15H2zM6 16l5-8m2 8 4-5"/>',wind:'<path d="M2 8h14a3 3 0 1 0-3-3M2 12h19M2 16h11a3 3 0 1 1-3 3"/>'};
export const svg=(id)=>`<svg viewBox="0 0 24 24" aria-hidden="true">${icons[id]||icons.gear}</svg>`;
export const parts=[
{id:'windshield',label:'Windshield',category:'Exterior · 01',title:'Clarity at every speed.',icon:'glass',point:[0,1.18,.5],camera:[2.4,2.1,3.4],target:[0,1.05,.45],description:'A curved laminated windshield combines a clear view of the road with a smooth path for air over the cabin.',features:['Two glass layers, bonded interlayer','Curvature guides airflow over the roof','Bonded glazing supports body rigidity','Rain sensors and camera integration vary by model'],note:'Educational overview. Driver-assistance equipment depends on the vehicle specification.'},
{id:'headlight',label:'Headlight',category:'Lighting · 02',title:'See the road differently.',icon:'light',point:[.71,.68,1.72],camera:[2,1.25,3.8],target:[.63,.67,1.65],description:'A compact optical housing brings together the main beam, dipped beam and daytime lighting. Light the way without losing the silhouette.',features:['LED daytime running-light signature','Precisely shaped reflectors and lenses','Sealed, aerodynamic housing','Adaptive or matrix functions depend on equipment'],demo:'Toggle headlights'},
{id:'wheel',label:'Wheel & Tire',category:'Contact patch · 03',title:'Performance meets the road.',icon:'wheel',point:[.98,.44,1.26],camera:[3.1,.95,2.7],target:[.85,.4,1.15],description:'Every input eventually reaches four small patches of rubber. A light wheel, a stiff sidewall and the right compound keep the car connected.',features:['Light alloy wheel construction','Tread channels water from the contact patch','Sidewall balances compliance and response','Correct pressure supports predictable grip'],demo:'Show brake system'},
{id:'brakes',label:'Brake System',category:'Chassis · 04',title:'Confidence under pressure.',icon:'wheel',point:[1,.4,1.16],camera:[2.6,.7,1.85],target:[.88,.4,1.2],description:'Hydraulic pressure moves caliper pistons, pressing friction pads against the rotating disc. Vehicle motion becomes heat that must be managed.',features:['Caliper applies even clamping force','Ventilated disc carries heat away','Pads provide controlled friction','Brake ducts deliver cooling airflow'],demo:'Technical view'},
{id:'engine',label:'Engine Area',category:'Powertrain · 05',title:'The heart sits at the back.',icon:'gear',point:[0,.91,-1.55],camera:[3.3,2.4,-4.1],target:[0,.7,-1.45],description:'The 911’s distinctive layout places its flat-six engine behind the rear axle. Opposed cylinders keep the engine compact and its mass low.',features:['Rear-mounted flat-six layout','Intake delivers filtered air','Cooling circuit manages engine temperature','Transmission sends torque to the driven wheels'],note:'Technical mode shows a simplified teaching model, not a service diagram.',demo:'Technical view'},
{id:'wing',label:'Rear Wing',category:'Aerodynamics · 06',title:'Make the air work harder.',icon:'wind',point:[0,1.45,-1.85],camera:[3.5,2.5,-4.4],target:[0,1.2,-1.7],description:'An inverted wing generates aerodynamic load. Its profile and angle influence the balance between downforce and drag.',features:['Airflow creates a pressure difference','Downforce adds high-speed tire loading','Endplates manage tip vortices','Angle of attack changes the aero balance'],demo:'Visualize airflow'},
{id:'tools',label:'Workshop Tools',category:'Craft · 07',title:'The right tool. Every time.',icon:'tool',point:[-3.8,1.05,1.6],camera:[-.9,2.1,4.3],target:[-3.8,1.1,1.1],description:'Good workmanship starts with careful measurement and tools chosen for the task. A tidy bench makes precise work easier to repeat.',features:['Torque wrench controls tightening torque','Sockets match the fastener size','Impact tools speed up suitable operations','Final tightening follows the service specification'],workshop:true},
{id:'equipment',label:'Service Equipment',category:'Diagnostics · 08',title:'Understand before you adjust.',icon:'lift',point:[4.7,1.5,-2.5],camera:[2.2,2.5,1],target:[4.7,1.1,-2.5],description:'Diagnostics combine electronic data with physical inspection. A fault code provides a direction for investigation, not a diagnosis on its own.',features:['Scan tools read fault codes and live data','Alignment checks wheel geometry','Battery testers measure starting capability','Inspection confirms the cause before repair'],workshop:true},
{id:'lift',label:'Hydraulic Lift',category:'Workshop · 09',title:'A better perspective.',icon:'lift',point:[2.9,1.7,-.8],camera:[5.8,3.2,3.8],target:[2.7,1.4,-.5],description:'A two-post lift raises the vehicle from approved support points. Mechanical locks support the raised load during service.',features:['Hydraulic cylinders provide lifting force','Lift arms contact approved lifting points','Mechanical locks secure the working height','Capacity and load balance must be checked'],demo:'Demonstrate lift',workshop:true},
{id:'tires',label:'Tire Station',category:'Rubber & road · 10',title:'Grip begins here.',icon:'wheel',point:[4.7,.9,2],camera:[2.3,1.7,4.5],target:[4.7,.7,1.9],description:'A tire is an engineered composite of rubber, steel and fabric. Its construction sets the foundation for grip, comfort and durability.',features:['Steel belts stabilize the tread','Carcass carries the load','Bead seals the tire to its wheel','Compound and tread suit different conditions'],workshop:true},
{id:'torque',label:'Torque Wrench',category:'Precision · 11',title:'Tight means measured.',icon:'tool',point:[-3.8,1.31,1.3],camera:[-2.9,2.1,2.7],target:[-3.8,1.3,1.25],description:'A torque wrench applies a specified rotational force to a fastener. Correct torque helps produce the intended clamp load.',features:['Set the specified torque value','Use the correct socket and technique','Follow the required tightening sequence','Keep the tool calibrated'],workshop:true}
];
export const home={camera:[6.8,3.15,8.7],target:[-.65,.85,0],fov:43};
